<a href="https://colab.research.google.com/github/Haubm/Machine_Learning/blob/main/Start_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.33667356, -0.2759359 ,  1.0734078 ,  0.13127694,  0.3906427 ,
        -0.40563175, -0.40964884, -0.32677513, -0.07869974, -1.0975112 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.12715511, 0.06890979, 0.26563996, 0.10354549, 0.13420612,
        0.06052777, 0.06028512, 0.06549402, 0.0839343 , 0.03030228]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.804653

In [9]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2946 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1443 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1084 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0905 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0769 - accuracy: 0.9761


In [11]:
model.evaluate(x_test, y_test, verbose = 2)

313/313 - 1s - loss: 0.0805 - accuracy: 0.9763 - 1s/epoch - 4ms/step


[0.0805000439286232, 0.9763000011444092]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9946218e-09, 5.6957468e-08, 1.5264817e-06, 4.5445899e-04,
        2.5171540e-11, 1.4438406e-07, 3.9279514e-13, 9.9953151e-01,
        7.3759210e-08, 1.2180781e-05],
       [1.2613669e-08, 2.3058789e-04, 9.9972290e-01, 3.6794692e-05,
        1.0575145e-14, 6.6822727e-06, 8.7337391e-08, 4.1034713e-13,
        2.8870006e-06, 5.8284134e-14],
       [5.2167262e-09, 9.9981695e-01, 1.7807275e-05, 2.5379368e-06,
        7.3830747e-06, 2.0107814e-06, 2.8838406e-06, 1.3627393e-04,
        1.3947290e-05, 1.0481192e-07],
       [9.9953282e-01, 2.1393939e-08, 1.9991148e-05, 4.2052545e-07,
        1.3325330e-06, 1.4093499e-05, 3.5213228e-04, 1.2609222e-05,
        6.4499140e-08, 6.6587803e-05],
       [1.1439288e-05, 1.1042631e-08, 3.6642708e-05, 9.0111433e-07,
        9.9867165e-01, 1.5810783e-06, 5.4874134e-05, 1.7477849e-05,
        2.9807886e-06, 1.2024064e-03]], dtype=float32)>